fix: Angular 8 build error:
```
oidc-client/index.ts(39,19): Error during template compile of 'Log'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler.
```